AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "MyDynamoDBTable"
      AttributeDefinitions:
        - AttributeName: "PrimaryKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PrimaryKey"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED  # または "PAY_PER_REQUEST"
      SSESpecification:          # サーバーサイド暗号化を有効にする場合
        SSEEnabled: true
