AWSTemplateFormatVersion: 2010-09-09
Description: WAFv2 in us-east-1 for CloudFront

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Name Prefix and Environment
        Parameters:
          - ProjectName
          - Env
      - Label:
          default: WAF
        Parameters:
          - WebACLScope
          - PrismaAccessAllowAddresses
          - SecurePCAllowAddresses
          - 1stKidsAllowAddresses
          - KDSAllowAddresses
          - IRETAllowAddresses
          - KITBastionAllowAddresses
          - TestAllowAddresses
          - SecurityRoomAllowAddresses

Parameters:
  ProjectName:
    Type: String
    Default: voice-dx

  Env:
    Type: String
    Default: stg

  # WAF
  WebACLScope:
    Type: String
    Default: CLOUDFRONT

  PrismaAccessAllowAddresses:
    Description: PrismaAccess IP list to allow access
    Type: CommaDelimitedList

  SecurePCAllowAddresses:
    Description: SecurePC IP list to allow access
    Type: CommaDelimitedList

  1stKidsAllowAddresses:
    Description: 1stKids IP list to allow access
    Type: CommaDelimitedList

  KDSAllowAddresses:
    Description: KDS IP list to allow access
    Type: CommaDelimitedList

  IRETAllowAddresses:
    Description: IRET IP list to allow access
    Type: CommaDelimitedList

  KITBastionAllowAddresses:
    Description: KIT Bastion IP list to allow access
    Type: CommaDelimitedList

  TestAllowAddresses:
    Description: Test IP list to allow access
    Type: CommaDelimitedList

  SecurityRoomAllowAddresses:
    Description: SecurityRoom IP list to allow access
    Type: CommaDelimitedList

  WafLogBucketName:
    Type: String
    Default: ""

Conditions:
  IsStgPrd: !Or [!Equals [!Ref Env, "stg"], !Equals [!Ref Env, "prd"]]
  IsDevStg: !Or [!Equals [!Ref Env, "dev"], !Equals [!Ref Env, "stg"]]

Resources:
  WAFv2WebACL:
    Type: AWS::WAFv2::WebACL
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${Env}-${ProjectName}-acl
      Description: !Sub ${Env}-${ProjectName}-acl
      DefaultAction: !If
        - IsDevStg
        - Block: {}
        - Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${Env}-${ProjectName}-acl
      Scope: !Ref WebACLScope
      Rules: !If
        - IsDevStg
        - - Name: !Sub ${Env}-${ProjectName}-portal-rule
            Priority: 0
            Action:
              Allow: {}
            Statement:
              OrStatement:
                Statements:
                  - IPSetReferenceStatement:
                      Arn: !GetAtt IPWhiteListPrismaAccess.Arn
                  - IPSetReferenceStatement:
                      Arn: !GetAtt   IPWhiteListSecurityRoom.Arn
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: !Sub ${Env}-${ProjectName}-portal-rule
        - !Ref "AWS::NoValue"

  # IP Sets
  ## Prisma Access
  IPWhiteListPrismaAccess:
    Type: AWS::WAFv2::IPSet
    Condition: IsDevStg
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${Env}-${ProjectName}-prisma-access-ipsets
      IPAddressVersion: IPV4
      Addresses: !Ref PrismaAccessAllowAddresses
      Scope: !Ref WebACLScope

  ## KIT Bastion
  IPWhiteListKITBastion:
    Type: AWS::WAFv2::IPSet
    Condition: IsStgPrd
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${Env}-${ProjectName}-kit-bastion-ipsets
      IPAddressVersion: IPV4
      Addresses: !Ref KITBastionAllowAddresses
      Scope: !Ref WebACLScope

  ## KDDI/IRETセキュリティルーム
  IPWhiteListSecurityRoom:
    Type: AWS::WAFv2::IPSet
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${Env}-${ProjectName}-security-room-ipsets
      IPAddressVersion: IPV4
      Addresses: !Ref SecurityRoomAllowAddresses
      Scope: !Ref WebACLScope