name: test infra dev-release

on:
  push:
    branches:
      - develop

jobs:
  deploy-development:
    environment: dev
    runs-on: [self-hosted]
    env:
      ENV: dev
      ProjectName: test
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: pip install
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy CFn
        run: |
          python deploy.py
      # - name: Deploy Lambda
      #   run: |
      #     sh lambda_deploy.sh
