name: test infra dev-release

on:
  push:
    branches:
      - develop

jobs:
  deploy-development:
    environment: dev
    runs-on: ubuntu-latest
    env:
      ENV: dev
      ProjectName: voice-km
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Checkout
        uses: actions/checkout@v2.3.2
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      - name: pip install
        run: |
          python -m venv ./venv
          source ./venv/bin/activate
          # echo "PATH=${PATH}" >> "${GITHUB_ENV}"
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy CFn
        run: |
          python deploy.py
      # - name: Deploy Lambda
      #   run: |
      #     sh lambda_deploy.sh
